# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [ ]:
import numpy as np

In [ ]:
#Creating sample array
arr=np.arange(0,21)

In [ ]:
#Show
arr

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
import numpy as np

In [ ]:
#Creating sample array
arr=np.arange(0,21)
arr

In [ ]:
#Get a value at an index
arr[9]

In [ ]:
#Get values in a range
arr[1:11:2]

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
arr

In [ ]:
arr=np.arange(21)

In [ ]:
arr2=arr.copy() # creating a backup

In [ ]:
#Setting a value with index range (Broadcasting)
arr2[0:10]=100

#Show
arr2

In [ ]:
arr

In [ ]:
arr

In [ ]:
arr=arr+20-100


In [ ]:
import numpy as np
arr = np.arange(21)

In [ ]:
arr

In [ ]:
arr + arr  # same as arr*2

In [ ]:
arr-arr

In [ ]:
arr

In [ ]:
arr/arr

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([3,4,5])

In [ ]:
arr1 + arr2

In [ ]:
arr3=np.zeros(21)
arr3.size

In [ ]:
arr/arr3

In [ ]:
arr3=arr.copy() # preserving the original array
arr3

In [ ]:
arr3[10:]=50
arr3

In [ ]:
arr

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr1

In [ ]:
arr2=np.array([4,5,6])

In [ ]:
arr2

In [ ]:
# list1 + list2 ~ concatenation... [1,2,3,4,56]

In [ ]:
arr1+arr2

In [ ]:
arr1-arr2

In [ ]:
arr1*arr2

In [2]:
import numpy as np

In [7]:
# Filtering condition 

arr=np.array([1,2,1010,4,108,18,71,610.56])
arr

array([1.0000e+00, 2.0000e+00, 1.0100e+03, 4.0000e+00, 1.0800e+02,
       1.8000e+01, 7.1000e+01, 6.1056e+02])

In [8]:
np.where(arr>100) # where function outputs index location of values
# meeting the condition

(array([2, 4, 7], dtype=int64),)

In [5]:
np.where(arr<100)

(array([0, 1, 3, 5, 6], dtype=int64),)

In [6]:
np.where(arr==100)

(array([], dtype=int64),)

In [ ]:
# copy operation
arr=np.array([1,2,3,4,5])

In [ ]:
arr[3:]=100

In [ ]:
arr

In [ ]:
arr1=arr # assigning the elements of arr to arr1 # backup

In [ ]:
arr

In [ ]:
arr1

In [ ]:
arr1[3:]=500

In [ ]:
arr1 # new array

In [ ]:
arr

In [ ]:
arr2=arr.copy()

In [ ]:
arr

In [ ]:
arr2

In [ ]:
arr2[3:]=100

In [ ]:
arr2

In [ ]:
arr # rstored the property of backup.

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. It is recommended to use the comma notation for clarity.

In [ ]:
import numpy as np

In [9]:
arr_2d = np.array(([1,2,3],[12,15,18],[64,96,128]))

#Show
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [12]:
arr_2d[1]  # 2nd row (index value 1)

array([12, 15, 18])

In [13]:
arr_2d[:,2]

array([  3,  18, 128])

In [ ]:
arr_2d[:,:2]

In [ ]:
arr_2d[1:,1:]

In [ ]:
arr_2d[1,1]

In [ ]:
arr_2d[2][2]

In [ ]:
arr_2d[1:,:2]

In [ ]:
arr_2d[1][1]

In [ ]:
arr_2d[0:2,0:2]

In [ ]:
arr_2d[0:2][0:2]

In [ ]:
arr_2d[:,1]

In [ ]:
#Indexing row
arr_2d[1]


In [ ]:
# Indexing column
arr_2d[:,2]

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

In [ ]:
# Getting individual element value
arr_2d[1,0]

In [ ]:
arr_2d

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

In [ ]:
#Shape bottom row
arr_2d[2]

In [ ]:
#Shape bottom row
arr_2d[2,:]

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [14]:
arr1=np.ones((10,10))
arr1.shape

(10, 10)

In [15]:
#Set up matrix
arr2d = np.zeros(arr1.shape)  # taking shape from an existing array

In [16]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
arr2d.shape

(10, 10)

In [19]:
no_of_rows=arr2d.shape[0]

In [ ]:
no_of_rows

In [20]:
#Set up array

for i in range(no_of_rows):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [21]:
arr2d[:,[6,4,5]]

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.],
       [8., 8., 8.],
       [9., 9., 9.]])

In [ ]:
arr2d

In [22]:
arr2d[[6,3,8]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
arr2d[[2,4,6,8]]

In [ ]:
arr2d[:,[2,4,6,8]]

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [23]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[:,0]<4

# Happy Learning!