# NumPy Operations

## Arithmetic

You can perform array operations with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [ ]:
import numpy as np
arr = np.arange(0,20)
arr

In [ ]:
arr + arr

In [ ]:
arr*3

In [ ]:
list1=[1,2,3]

In [ ]:
list1

In [ ]:
list1*2 

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
arr

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan-->not a number
arr/arr

In [ ]:
# Also warning, but not an error instead infinity(Reciprocal)
1/arr

In [ ]:
arr

In [ ]:
arr**3 ## power of operator

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [2]:
import numpy as np
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
arr**2  # square of arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361], dtype=int32)

In [3]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [5]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [6]:
np.max(arr) #same as arr.max()

19

In [7]:
np.log(arr) # default base for log is e

C:\Users\Dell\AppData\Local\Temp\ipykernel_4212\1036463842.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # default base for log is e


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [8]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [9]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
       -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462])

In [ ]:
import numpy as np

In [15]:
## conversion from degree to radians
d=np.arange(0,120,30).reshape(2,2)
d

array([[ 0, 30],
       [60, 90]])

In [16]:
np.rad2deg(d)

array([[   0.        , 1718.87338539],
       [3437.74677078, 5156.62015618]])

In [12]:
arr3=np.radians(d)  # degrees to radians
arr3

array([[0.        , 0.52359878],
       [1.04719755, 1.57079633]])

In [13]:
np.degrees(arr3)

array([[ 0., 30.],
       [60., 90.]])

In [14]:
np.rad2deg(arr3)

array([[ 0., 30.],
       [60., 90.]])

In [ ]:
rad=d*np.pi/180  # formula

In [ ]:
rad

In [ ]:
rad1=np.radians(d)
rad1

In [ ]:
d1=np.degrees(rad1)

In [ ]:
d1

In [ ]:
deg_rad1=np.rad2deg(rad1)

In [ ]:
deg_rad1

In [ ]:
# np.Sec(rad)

In [ ]:
https://numpy.org/devdocs/user/absolute_beginners.html