# NumPy 
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you dont have Anaconda, install NumPy by going to your terminal or command prompt and type:**
    
    !pip install numpy
    conda install numpy
    


In [ ]:
!pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. 

# Numpy Arrays

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

The following cells explain on creation of NumPy arrays.

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [1]:
import numpy as np

In [3]:
arr1 = np.array([])   # create an empty array
arr1

array([], dtype=float64)

In [4]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [7]:
tup1 = (54,34,22)
np.array(tup1)

array([54, 34, 22])

In [9]:
tup1

(54, 34, 22)

In [5]:
a=np.array(my_list)

In [18]:
a

array([1, 2, 3, 4, 5])

In [8]:
type(a)   # ndarray is number dimension array

numpy.ndarray

In [ ]:
type(a)

In [10]:
a.ndim  # number of dimensions in the array

1

In [11]:
a.size  # size of an array is the no. of items 

5

In [19]:
a.shape

(5,)

In [12]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [13]:
b=np.array(my_matrix)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
type(b)

numpy.ndarray

In [15]:
b.ndim   # no. of dimensions

2

In [17]:
b.size  # no. of elements

12

In [16]:
b.shape  # for 2d array, rows and cols

(3, 4)

In [22]:
arr1= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr1.shape

(2, 2, 3)

In [29]:
arr2=arr1.reshape((1,3,4))  # reshape function takes the new shape as its argument

In [30]:
arr2.shape

(3, 4)

In [28]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [24]:
arr1.ndim

3

In [25]:
arr1.size

12

In [26]:
arr1.dtype  # datatype of the elements 

dtype('int32')

In [ ]:
arr2 = np.array([2,3,4,5])
arr2

In [ ]:
arr2.shape

In [ ]:
arr3 = np.array([[2,3,4,5]])
arr3

In [ ]:
arr3.shape

In [ ]:
# function that can tell if a number is prime or composite
def prime(num):
    for i in range(2,num):

In [31]:
arr1 =np.zeros((3,4))
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
arr1.dtype

dtype('float64')

In [36]:
var1 = 25.6
isinstance(var1,float)   # check whether var1 is an instance of integer  

True

In [33]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.ones((2,4,5), dtype=int)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [ ]:
# Array summary
print('The Dimenesion of array',b.ndim) # dimensions of givene array

In [ ]:
print('The size of array:',b.size) # Number of elements in array

In [ ]:
print('The datatype of element:',b.dtype) # Datatype of elements of array

In [ ]:
print('The datatype of array',type(b))

In [ ]:
print('The shape:',a.shape)

In [ ]:
b.shape

In [ ]:
a # 1 dimensional array

In [ ]:
b

In [ ]:
c=np.array([[[[1,2,3,4,5],[6,7,8,9,10]]]])
c

In [ ]:
c.ndim

In [ ]:
c.shape

In [ ]:
c.size

In [ ]:
c.shape

In [ ]:
c.ndim

In [ ]:
np.ones((2,2))

In [1]:
import numpy as np

In [2]:
big_one=np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
big_one.dtype

dtype('float64')

In [4]:
list1=[2,3,4,5,6]
list1*2


[2, 3, 4, 5, 6, 2, 3, 4, 5, 6]

In [5]:
big_one * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### The ability to access each and every element of an array is known as Broadcasting.

In [6]:
bigger_one=big_one*6 - 2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [7]:
bigger_one * 2 - 3

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [8]:
big_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
bigger=np.array(big_one*3 - 0.4, dtype='int')
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [10]:
bigger.dtype

dtype('int32')

In [11]:
type(bigger)

numpy.ndarray

In [ ]:
bigger2= np.array(bigger, dtype='int')

In [ ]:
bigger2

In [ ]:
np.ones((4,5))

In [12]:
bigger.shape

(3, 4)

In [14]:
# Generating random samples of 
np.random.random_sample(bigger.shape) # borrowing shape of existing array

array([[0.88543929, 0.77350791, 0.75214044, 0.54734871],
       [0.99175948, 0.0200094 , 0.43603513, 0.34868243],
       [0.36635361, 0.91619389, 0.48689368, 0.07053239]])

In [14]:
# Generating random samples of 
np.random.random_sample((4,7))

array([[0.88543929, 0.77350791, 0.75214044, 0.54734871],
       [0.99175948, 0.0200094 , 0.43603513, 0.34868243],
       [0.36635361, 0.91619389, 0.48689368, 0.07053239]])

In [15]:
10*np.random.random_sample(bigger.shape)

array([[7.07708505, 6.74588564, 1.37929705, 0.27380355],
       [3.67215454, 0.99022092, 6.24430955, 3.39030704],
       [3.74180372, 9.74167273, 2.16604733, 9.18717777]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [16]:
np.arange(15) # end; default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.arange(1,15.5) # start and end

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [19]:
np.arange(100,2,-4) # start, end and step

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [20]:
np.arange(0,11,2) # start end and step

array([ 0,  2,  4,  6,  8, 10])

### Reshape function

In [21]:
np.arange(1,16)  # 1 to 15

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
np.arange(1,16).shape

(15,)

In [25]:
# reshape serves to change the existing shape of the array
np.arange(1,16).reshape(1,1,3,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [26]:
arr1=np.arange(18) # 0 to 17 gives us 18 elements
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [27]:
arr2 = arr1  # not a typical way to create a new array

In [28]:
arr2= arr2*2 - 2
arr2

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
       32])

In [29]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
arr1.ndim

In [ ]:
arr2.ndim

In [ ]:
arr=np.zeros((3,4))
arr

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
import numpy as np

In [ ]:
np.zeros(3) # Generates array in 1 dimension with all elements 0

In [ ]:
np.zeros((5,5))  # Generates array in 2 diemnsion with all elements 0

In [ ]:
np.zeros((4,3,5))

In [ ]:
np.ones(3) # Generates array of 1 dimension where all elements are 1

In [ ]:
np.ones((3,3)) # Generates array of 2 dimension where all elements are 1

In [ ]:
np.ones((4,5,6))

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
import numpy as np

In [30]:
np.linspace(1,15)  # default 50 observations
# both the start and end are included in the array

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [31]:
np.linspace(5,25,10)  # equally spaced 10 values

array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
       16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ])

In [ ]:
# retstep ~ return step computed by linspace

In [32]:
np.linspace(0,25, retstep=True) # Start # end (Here end is included) and default elements are 50

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 0.5102040816326531)

In [ ]:
np.linspace(0,200,10,retstep=True) 

In [ ]:
np.linspace(0,200,10)

In [ ]:
np.linspace(0,200,10,retstep=True)

## eye

Creates an identity matrix

In [42]:
np.eye(5)   # generates 2d array of (5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Create an eye from a zeros array

In [33]:
arr1= np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr2 = arr1 # not recommended
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
arr2[:10] = 30  # using indexing/slicing to modify arr2
arr2

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
arr1

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
arr3 = arr1.copy() # generate a copy 

In [40]:
arr3[10:] = 100
arr3

array([ 30,  30,  30,  30,  30,  30,  30,  30,  30,  30, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [41]:
arr1  # copy function retains the original. copy creates a backup array.

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [1]:
import numpy as np

In [3]:
np.random.rand(10) # rand gives values between 0 and 1

array([0.46668193, 0.03272958, 0.32554694, 0.70787635, 0.6562855 ,
       0.33169436, 0.54718121, 0.24661537, 0.88475696, 0.81665872])

In [ ]:
# Creating array from uniform distribution
new_arr=np.random.rand(5,3)
# 2 dimensional array of shape (5,3)

In [ ]:
new_arr

In [4]:
np.random.rand(3,3)

array([[0.25408657, 0.38824774, 0.47576792],
       [0.20099291, 0.09607117, 0.62230647],
       [0.02015345, 0.69094166, 0.24026649]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
# For randn, random numbbers generated will be in approximately -3 to +3 range.

In [9]:
arr1=np.random.randn(100)  # 50 observations from std normal distribution
arr1

array([-0.28825955, -0.16608574,  0.1271808 ,  0.79656999, -1.1390174 ,
        2.62719954, -0.84969919, -1.16704614, -1.60440815,  0.83339834,
        0.71598313, -0.03884732, -0.69179102,  0.63887661,  2.77125411,
       -1.37006731,  0.83653134,  0.15444525, -0.04667715,  0.30057631,
        0.6230956 , -0.91467011, -1.30564999, -0.59311855,  0.1091833 ,
        0.33028858, -0.19193936, -0.76070742,  0.89178494,  0.98449161,
       -0.86954625,  0.87955933,  2.56389361,  0.29948775,  1.82871293,
       -0.02573029, -0.43789614,  0.7773041 ,  0.84880566, -1.04097706,
       -0.18914829, -1.07429575, -0.69422992,  2.15627857, -0.52337765,
       -0.24908029, -0.87721165, -2.15176054, -0.60305856, -1.61238803,
       -0.57912018,  2.13637921,  0.4329672 ,  0.80260128, -0.41173827,
        2.08903234,  0.27475494,  0.98483194, -1.48656981,  0.60640049,
        0.34858233,  0.15018365,  0.96905274, -0.2613964 ,  1.33193872,
       -0.36249624, -0.40556701, -0.0709972 , -0.99972456, -0.69

In [10]:
max(arr1)

2.771254113594133

In [11]:
min(arr1)

-2.1517605393249477

In [ ]:
np.random.randn(3,3)

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [12]:
np.random.randint(1,100) 
# third argument is no. of values. default =1 value

24

In [13]:
np.random.randint(1,100,10)

array([90, 57, 17, 78, 60, 22, 81, 93, 69, 89])

In [14]:
np.random.randint(40,60,50) # generating 50 values between 

array([45, 50, 54, 59, 48, 48, 53, 55, 48, 49, 53, 49, 49, 41, 50, 45, 54,
       49, 56, 42, 52, 58, 48, 45, 45, 55, 40, 48, 59, 53, 40, 55, 52, 57,
       47, 47, 45, 58, 55, 49, 49, 43, 43, 56, 59, 55, 49, 54, 48, 42])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [15]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
ranarr

array([60, 77, 46, 60, 37, 30, 59, 55, 17, 15])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [18]:
ranarr

array([60, 77, 46, 60, 37, 30, 59, 55, 17, 15])

In [19]:
ranarr.max() # highest element of the array

77

In [21]:
arr.max()

19

In [22]:
ranarr.argmax() ## Index location of highest element

1

In [20]:
ranarr.min() # Gives the lowest element of array

15

In [23]:
ranarr.argmin() # Index location of lowest element

9

In [24]:
ran2=ranarr.reshape(2,5)

In [25]:
ran2

array([[60, 77, 46, 60, 37],
       [30, 59, 55, 17, 15]])

In [27]:
ran2.argmax()

1

In [26]:
ran2.max()

77

# Happy Learning!